# Generated by Django 4.0.5 on 2022-07-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avartar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avartar',
            new_name='avatar',
        ),
    ]
